### ISSUE TITLE
How to use framework

### ISSUE THREAD

**Issue by SpaceKadet2** [ChrisKlinkmueller/Ethereum-Logging-Framework#27]
Hello, I followed all the steps in the read me file and I cannot seem to get this working properly. I 100% believe it is my own user error but I just don't know where to go once I finish the instructions in the readme document. How do I actually use this to extract data from the blockchain? 
I am currently doing a project on process mining on Axie Infinity and this is a huge portion of the project here. Any guidance is helpful. 

Sincerely a college student.

**Comment by ChrisKlinkmueller** [comment]
Hi, please have a look at the [blockchain logging framework](https://github.com/TU-ADSP/Blockchain-Logging-Framework). It is an extension that was tested thoroughly, comes with improvements and is well documented. The [wiki](https://github.com/TU-ADSP/Blockchain-Logging-Framework/wiki/Manifest) provides detailed instructions on how to use the framework to extract data from public Ethereum. Hope this helps you to get started.
